version: '3'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.backend
    environment:
      - APP_ENV=dev
    ports:
      - "40001:40001"
    volumes:
     - ./backend:/code